"use client";

import { useEffect, useMemo, useState } from "react";
import { RefreshCw } from "lucide-react";
import type { CalendarEvent } from "@/types/domain";
import { StatusMessage } from "@/components/ui/status-message";

function normalizeImpact(value: unknown): CalendarEvent["impact"] { const text = String(value ?? "").toLowerCase(); if (text.includes("high") || text.includes("3")) return "high"; if (text.includes("medium") || text.includes("2")) return "medium"; return "low"; }
function normalizeEvent(item: Record<string, unknown>): CalendarEvent { return { date: String(item.date ?? ""), datetime: String(item.datetime ?? item.datetime_utc ?? item.date_time ?? item.timestamp ?? ""), time: String(item.time ?? item.event_time ?? "--:--"), currency: String(item.currency ?? item.country_code ?? item.currency_code ?? "USD").toUpperCase(), impact: normalizeImpact(item.impact ?? item.importance ?? item.volatility), event: String(item.event ?? item.title ?? item.name ?? "Economic Event"), actual: (item.actual ?? item.actual_value ?? "-") as string | number | null, forecast: (item.forecast ?? item.forecast_value ?? item.estimate ?? "-") as string | number | null, previous: (item.previous ?? item.previous_value ?? item.prev ?? "-") as string | number | null, country: String(item.country ?? item.zone ?? item.region ?? "Global") }; }

export function CalendarClient() {
  const [events, setEvents] = useState<CalendarEvent[]>([]); const [range, setRange] = useState("today"); const [impact, setImpact] = useState("all"); const [currency, setCurrency] = useState("all"); const [message, setMessage] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function load() { setLoading(true); setMessage(null); try { const response = await fetch(`/api/economic-calendar?range=${encodeURIComponent(range)}`, { cache: "no-store" }); if (!response.ok) throw new Error("Sumber kalender belum dikonfigurasi atau gagal merespons."); const payload = await response.json() as unknown; const rows = Array.isArray(payload) ? payload : Array.isArray((payload as { data?: unknown[] }).data) ? (payload as { data: unknown[] }).data : []; setEvents(rows.map((item) => normalizeEvent(item as Record<string, unknown>))); } catch (error) { setMessage(error instanceof Error ? error.message : "Gagal memuat kalender."); setEvents([]); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [range]);
  const visible = useMemo(() => events.filter((item) => (impact === "all" || item.impact === impact) && (currency === "all" || item.currency === currency)), [events, impact, currency]); const currencies = [...new Set(events.map((item) => item.currency))].sort();
  return <div className="grid gap-6"><section className="hero-card"><div><p className="eyebrow">Economic Calendar</p><h1>Kalender Ekonomi</h1><p>Feed event ekonomi melalui backend proxy/Edge Function; tidak ada API secret di browser.</p></div><button className="ghost-button" onClick={load} disabled={loading}><RefreshCw className={loading ? "size-4 animate-spin" : "size-4"} />Refresh</button></section><section className="panel grid gap-4 md:grid-cols-3"><label className="grid gap-2"><span>Range</span><select value={range} onChange={(e) => setRange(e.target.value)}><option value="today">Today</option><option value="tomorrow">Tomorrow</option><option value="week">This Week</option><option value="past-month">Last 30D</option><option value="next-month">Next 30D</option></select></label><label className="grid gap-2"><span>Impact</span><select value={impact} onChange={(e) => setImpact(e.target.value)}><option value="all">Semua impact</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label className="grid gap-2"><span>Currency</span><select value={currency} onChange={(e) => setCurrency(e.target.value)}><option value="all">Semua currency</option>{currencies.map((item) => <option key={item}>{item}</option>)}</select></label></section><StatusMessage tone="info">{message}</StatusMessage><section className="panel overflow-hidden p-0"><div className="overflow-auto"><table className="data-table"><thead><tr><th>Tanggal</th><th>Waktu</th><th>Currency</th><th>Impact</th><th>Event</th><th>Actual</th><th>Forecast</th><th>Previous</th></tr></thead><tbody>{visible.map((item, index) => <tr key={`${item.date}-${item.event}-${index}`}><td>{item.date || "—"}</td><td>{item.time}</td><td><strong>{item.currency}</strong></td><td><span className={`impact ${item.impact}`}>{item.impact}</span></td><td>{item.event}</td><td>{String(item.actual ?? "-")}</td><td>{String(item.forecast ?? "-")}</td><td>{String(item.previous ?? "-")}</td></tr>)}</tbody></table>{!visible.length && <div className="empty-state">Belum ada event dari sumber kalender.</div>}</div></section></div>;
}
